import { getOptionalEnv, getRequiredEnv } from '../utils/env.js';

const TOKEN_SECRET = getRequiredEnv('TOKEN_SECRET');
const TOKEN_EXPIRES_IN = getOptionalEnv('TOKEN_EXPIRES_IN');
const REFRESH_TOKEN_SECRET = getRequiredEnv('REFRESH_TOKEN_SECRET');
const REFRESH_TOKEN_EXPIRES_IN = getOptionalEnv('REFRESH_TOKEN_EXPIRES_IN');

const SIGNUP_CODE_EXPIRES_IN = 5;
const SIGNUP_SUBJECT = 'Foodeez Email Verification';

const PASSWORD_RESET_CODE_EXPIRES_IN = 15;
const PASSWORD_CHANGE_TOKEN_EXPIRES_IN = '15m';
const INVALID_CREDENTIALS_ERROR = 'Invalid credentials';
const INVALID_REQUEST_ERROR = 'Invalid request';
const PASSWORD_RESET_SUBJECT = 'Foodeez Email Verification';

export {
    TOKEN_SECRET,
    TOKEN_EXPIRES_IN,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRES_IN,
    SIGNUP_CODE_EXPIRES_IN,
    SIGNUP_SUBJECT,
    PASSWORD_RESET_CODE_EXPIRES_IN,
    PASSWORD_CHANGE_TOKEN_EXPIRES_IN,
    PASSWORD_RESET_SUBJECT,
    INVALID_CREDENTIALS_ERROR,
    INVALID_REQUEST_ERROR
};
