//Auth controller
const TOKEN_SECRET ="GF5JpZGZYJGGIHhnIphb";
const TOKEN_EXPIRES_IN ="1m";
const REFRESH_TOKEN_SECRET ="GF5JpZGZYJGGIHhnIphbXXXXXXAFDASDFS";
const REFRESH_TOKEN_EXPIRES_IN ="5m";

//Signup controller
const SIGNUP_CODE_EXPIRES_IN=5;  /* in minutes */

const INVALID_CREDENTIALS_ERROR="Invalid credentials";
const INVALID_REQUEST_ERROR="Invalid request";
 
export  { 
    TOKEN_SECRET, 
    TOKEN_EXPIRES_IN,
    REFRESH_TOKEN_SECRET, 
    REFRESH_TOKEN_EXPIRES_IN,
    SIGNUP_CODE_EXPIRES_IN,
    INVALID_CREDENTIALS_ERROR,
    INVALID_REQUEST_ERROR
}